
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/monoholy
    username: test_admin
    password: 123monoholy123
    driver-class-name=org: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

  mvc:
    path-match:
      matching-strategy: ant_path_matcher

server:
  servlet:
    session:
      cookie:
        max-age: 30m